name: iwent
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  carousel_pro: ^0.0.13

  cupertino_icons: ^0.1.2

  bloc_pattern: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/iwent-logo.png
    - assets/fb-icon.png
    - assets/iw-icon.png
    - assets/HomeWidget/carousel/1.jpg
    - assets/HomeWidget/carousel/2.jpg
    - assets/HomeWidget/carousel/3.jpg
    - assets/RegisterWidget/email-icon.png
    - assets/RegisterWidget/password-icon.png
    - assets/RegisterWidget/infos-icon.png

  fonts:
      - family: Lobster
        fonts:
          - asset: fonts/Lobster-Regular.ttf
      - family: Oswald
        fonts:
          - asset: fonts/Oswald[wght].ttf
      - family: Righteous
        fonts:
          - asset: fonts/Righteous-Regular.ttf
      - family: Overpass
        fonts:
          - asset: fonts/Overpass-Light.ttf 


  uses-material-design: true
