name: iwent
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  carousel_pro: ^0.0.13

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/iwent-logo.png
    - assets/fb-icon.png
    - assets/iw-icon.png
    - assets/carousel/1.jpg
    - assets/carousel/2.jpg
    - assets/carousel/3.jpg

  fonts:
      - family: Lobster
        fonts:
          - asset: fonts/Lobster-Regular.ttf
      - family: Oswald
        fonts:
          - asset: fonts/Oswald[wght].ttf
      - family: Righteous
        fonts:
          - asset: fonts/Righteous-Regular.ttf
      - family: Overpass
        fonts:
          - asset: fonts/Overpass-Light.ttf 


  uses-material-design: true
