name: flutter_social
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_icons: ^0.2.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
   - assets/images/man1.jpg
   - assets/images/man2.jpg
   - assets/images/man3.jpg
   - assets/images/man4.jpg
   - assets/images/man5.jpg
   - assets/images/woman1.jpg
   - assets/images/woman2.jpg
   - assets/images/woman3.jpg
   - assets/images/woman4.jpg
   - assets/images/woman5.jpg
   - assets/images/home_page.png
   - assets/images/logo.png
   - assets/images/empty.png
   - assets/images/post_banner.jpg
   - assets/images/iw-icon.png


  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
  
